### ISSUE TITLE
Number input not working with repeater

### ISSUE THREAD

**Issue by yankeyhotel** [CodyHouse/cd-repeater-changelog#1]
I have a repeater element with a [number input](https://codyhouse.co/ds/components/app/number-input) in it. The number input works well on load. However, when the repeater section is repeated, the new number input that is contained in that repeated element isn't working. The +/- buttons do not increase or decrease the number. And on load, the number input is blank instead of having a "0" in it. As far as I can tell, it looks like the new number input isn't being added to the `initInputNumberEvents` addEventListener.

I have checked and the elements have the `customName[n][inputType]` set correctly.

https://user-images.githubusercontent.com/1146801/197059989-b50ec60d-f3e6-4508-bece-56430fb70c57.mov

<img width="1022" alt="Screen Shot 2022-10-20 at 4 19 07 PM" src="https://user-images.githubusercontent.com/1146801/197060453-812bda0f-17e4-4c4d-8afe-69eebb1c4a8a.png">

**Comment by claudia-romano** [comment]
Hi there, you will need to initialise the new number input element each time a clone is created.
We have added a section to the Info page of the component about that:
https://codyhouse.co/ds/components/info/repeater#dynamic-content

You may need to use the ```data-default``` attribute for your number input (e.g. ```data-default="1"```):
https://codyhouse.co/ds/components/info/repeater#default-values

We have just pushed a new version of the repeater and Input Number components so please make sure to update both the js files. Thanks!

I'm closing this issue for the moment but feel free to reopen it if you are still having problems. Cheers!

**Comment by yankeyhotel** [comment]
Thank you!
