### ISSUE TITLE
Unexpected behavior when cloning Checkboxes / Radio

### ISSUE THREAD

**Issue by icecaster** [CodyHouse/cd-repeater-changelog#2]
The repeater component resets the value of cloned fields to empty / data-default attribute.

This causes checkboxes / radio to lose their value attribute (which may contain a boolean value to be submitted in the form)

Instead it should be checking for the "checked" attribute and reset that / use the data-default value

**Comment by icecaster** [comment]
Here's a fix that worked for me:

~L104

```

for(var i = 0; i < nameElements.length; i++) {
      var nameAttr = nameElements[i].getAttribute('name');
      nameElements[i].setAttribute('name', nameAttr.replace(nameToReplace, newName));
      if(reset) {
        if(nameElements[i].type == "checkbox" || nameElements[i].type == "radio") {
          nameElements[i].checked = nameElements[i].getAttribute('data-default') ? nameElements[i].getAttribute('data-default') : '';
        } else {
          if(nameElements[i].value) {
            nameElements[i].value = nameElements[i].getAttribute('data-default') ? nameElements[i].getAttribute('data-default') : '';
          }
        }
      }
    }
```

**Comment by claudia-romano** [comment]
Hi there, yes that makes sense!
We have updated the component to include this check; I have slightly modified your code to set the `checked` attribute to false rather than empty.

You can get the final code here:
https://codyhouse.co/ds/components/app/repeater

Cheers!

**Comment by icecaster** [comment]
Amazing, thank you!

Suggest a little tweak:

Change 
`
          nameElements[i].getAttribute('data-default') 
            ? nameElements[i].checked = nameElements[i].getAttribute('data-default')
            : nameElements[i].checked = false;
`

to 

`
          nameElements[i].checked = nameElements[i].getAttribute('data-default') ? nameElements[i].getAttribute('data-default') : false;
`

for consistency with other assignment.
